version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSOWRD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_USER: secret
    # Allows containers to talk to each other
    networks: 
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    # Exposes 8000 on local machine to 80 on the container
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: secret
    networks: 
      - wpsite
networks:
  wpsite:
volumes: 
  db_data:  


